version: "3"
services:
  sqliteweb:
    build: 
      context: .
      dockerfile: Dockerfile.sqliteweb
    ports:
      - 8080:8080    
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - dbdata:/dbdata
  heating:
    build: 
      context: .
      dockerfile: Dockerfile.heating
    restart: always
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - dbdata:/dbdata
  telegram:
    build: 
      context: .
      dockerfile: Dockerfile.telegram
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - dbdata:/dbdata
      - /var/run/dbus/:/var/run/dbus/:z
volumes:
  dbdata:
