FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3-pip python3-venv 
RUN pip3 install sqlite-web
EXPOSE 8080
CMD ["sqlite_web", "dbdata/heatcontrol.sqlite", "--read-only", "--host", "0.0.0.0"]
