FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3-pip python3-venv
RUN pip3 install pipx
RUN pipx install ruuvibot==0.2.6
COPY settings.json .

CMD ["/root/.local/bin/ruuvibot", "run"]
